[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "lib",
    "polygraphy~=0.49.9",
]

[tool.uv.sources]
lib = { path = "../lib", editable = true }
polygraphy = { index = "nvidia" }

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true